### ISSUE TITLE
Enhance the function

### ISSUE THREAD

**Issue by ExHix** [xingyujie/binpython#1]
Hello, I am an individual developer. I am looking forward an application to download protable version of python, and I find your repository. I was delighted but, I found that it requires a python-installed environment. I can't download python from the python official website directly due to some network forbiddance from my network operator, and I distrust any other third-party download channels because I afraid potential malware is embedded. Could you develope one that is indepentent of the requirement of python? Thanks a lot.

**Comment by EdwardLab** [comment]
Hi, great to see your issues.  Sorry I didn't quite understand what you meant by "developing a indepentent Python requirement".  Do you mean not using "pyinstaller" or something else?

**Comment by EdwardLab** [comment]
I read your request many times, but I don't understand what you mean, if you can't build, you can use the release version
