### ISSUE TITLE
Can you write the code in `binpython.py` in modules?

### ISSUE THREAD

**Issue by WhaleFell** [xingyujie/binpython#10]
You can import ~/common/xxx.py, write the functions of each module as a package, and then import it at the project entry file,integrating the command line by the way.

**Comment by WhaleFell** [comment]
This allows the program to be decoupled for easy maintenance later

**Comment by EdwardLab** [comment]
Thank you for your issues!  Yes, it can be done, but I feel like it's also possible now.  If I have time, I can change it like this :D

**Comment by WhaleFell** [comment]
Thank you for your reply and may God bless you.
