### ISSUE TITLE
希望有更详细的说明

### ISSUE THREAD

**Issue by hastonewy** [xingyujie/binpython#8]
首先我希望这个程序能作为虚拟环境来用，但我把想要用的库加入packagelist.txt但是编译后无效，不知是什么地方错了，这个方面也没看到有说明。。。

**Comment by EdwardLab** [comment]
好的，谢谢反馈，我将会编写更详细的说明

**Comment by EdwardLab** [comment]
现在有了，安排到仓库readme啦
