### ISSUE TITLE
希望有32位的版本

### ISSUE THREAD

**Issue by hbczmxy** [xingyujie/binpython#9]
希望作者能够编写一个能够支持32位系统的版本，比如在32位的Windows7系统中就无法使用您开发的BIN-Python。
另外，Linux系统的版本也是只支持64位的。

总感觉这样有些遗憾。
希望作者能够开发一下支持32位系统的版本。

**Comment by EdwardLab** [comment]
您好：
    首先非常感谢您反馈此问题，Python官方最新版将不再继续支持Windows8以下版本（包括Windows 7），我并不知道（也许）可以通过补丁等方法继续对Windows 7系统的Python支持，我在机房测试过Windows 7 64-bit可以正确运行BINPython，但似乎要重新在Windows 7下安装Python环境打包才能顺利运行（应该是缺了某些库），在Google上似乎有对此问题的解决方案，至于32-bit，非常抱歉，我没有32-bit系统的机器，因此也非常抱歉我也许暂时没法解决这个问题（如果有时间，我可以尝试虚拟机），如果可以，您可以参阅我们的文档（http://docs.binpython.org），并尝试自行编译（参考链接：http://docs.binpython.org/#/docs/build），若有任何问题，可以提问在此issue或提供任何信息，我将为您继续解答任何疑问，祝您一切顺利。
如果可以，我将尽可能提供32-bit的支持
感谢您的issue
谢谢！
至此，敬礼
